In [1]:
#Cahpter 2 Examples from "An Introduction to Quantum Computing" (Kaye, Leaflamme, Mosca)
#Worked with Qutip version 5.0.2 
#Numpy 
#Scipy 1.13.1 
#(and potentially other libraries) 
#Daequan Peele 
#June 2024 

#Lets get it.
#![title](images/imagename.png)

In [2]:
#imports
from qutip import *
import numpy as np


c:\Python312\Lib\site-packages\qutip\__init__.py:24: UserWarning: matplotlib not found: Graphics will not work.
  warnings.warn("matplotlib not found: Graphics will not work.")


![title](images/ex2_1_1.png)

In [3]:
#left hand side of the equation
lhs = np.sqrt(2/3) * basis(4,1) + (1j/np.sqrt(3)) * basis(4,3)

In [4]:
#right hand side of the equation 
rhs = tensor(np.sqrt(2/3) * basis(2,0), basis(2,1)) + tensor(1j/np.sqrt(3) * basis(2,1), basis(2,1))

#prove that lhs and rhs are equal 
np.allclose(lhs[:],rhs[:])

True

In [5]:
#LHS and RHS are equivalent. 

![title](images/ex2_2_2.png)

In [5]:
#create vectors 
phi = np.sqrt(2/3) * basis(4,1) + (1j/np.sqrt(3)) * basis(4,3)
psi = np.sqrt(1/2) * basis(4,2) + np.sqrt(1/2) * basis(4,3)

In [7]:
#dot product of |phi>* and |psi> is equal to the inner product of <phi | psi> 
#|phi>* is the conjugate transpose of column vector |phi> 
dot_product = phi.trans().conj() * psi 
print(dot_product)

-0.4082482904638631j


In [8]:
#<phi|psi>
inner_product = psi.overlap(phi.trans().conj()) 
print(inner_product)

-0.4082482904638631j


In [9]:
#inner product and dot product of transposed phi are equivalent 
dot_product == inner_product

True

![title](images/ex2_2_4.png)

In [10]:
#Define basis vectors of Hilbert dimension 4 
b1 = basis(4,0) # |00>
b2 = basis(4,1) # |01>
b3 = basis(4,2) # |10>
b4 = basis(4,3) # |11>
#print(b1, b2, b3, b4)

In [11]:
#inner product check < x | y >
ip1 = b1.overlap(b2.trans().conj()) 
ip2 = b1.overlap(b3.trans().conj()) 
ip3 = b1.overlap(b4.trans().conj()) 

ip4 = b4.overlap(b3.trans().conj()) 
ip5 = b2.overlap(b4.trans().conj())

ip6 = b3.overlap(b4.trans().conj()) 

print(ip1,ip2,ip3,ip4,ip5,ip6) #print inner product of any normal vector

-0j -0j -0j -0j -0j -0j


In [12]:
#norm check  
#norm is the square root of the inner product of a vector with itself sqrt(< x | x >)
n1 = np.sqrt(b1.overlap(b1.trans().conj()))
n2 = np.sqrt(b2.overlap(b2.trans().conj())) 
n3 = np.sqrt(b3.overlap(b3.trans().conj())) 
n4 = np.sqrt(b4.overlap(b4.trans().conj())) 

print(n1,n2,n3,n4) #print norms of each basis vector 

(1-0j) (1-0j) (1-0j) (1-0j)


In [13]:
#All inner products of the basis vectors are 0 and all norms of the basis vectors are 1

![title](images/ex2_2_5.png)

In [14]:
#Equation written in qubit 
np.sqrt(2/3) * np.sqrt(1/2) * b2.overlap(b3.trans().conj()) 

+ np.sqrt(2/3) * np.sqrt(1/2) * b2.overlap(b4.trans().conj())

+ (-1j/np.sqrt(3)) * np.sqrt(1/2) * b4.overlap(b3.trans().conj()) 

+ (-1j/np.sqrt(3)) * np.sqrt(1/2) * b4.overlap(b4.trans().conj()) 

#This equation should equal the dot product (or inner product) obtained from 2.2.2 


-0.4082482904638631j

In [15]:
print(dot_product)

-0.4082482904638631j


![title](images/ex2_2_6.png)

In [6]:
#Hadamard Basis: 
(1/np.sqrt(2)) * (basis(2,0) + basis(2,1)) # |+> 

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0.70710678]
 [0.70710678]]

In [17]:
(1/np.sqrt(2)) * (basis(2,0) - basis(2,1)) # |->

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[ 0.70710678]
 [-0.70710678]]

In [18]:
#Normality = < + | - > = 0
pos1 = basis(2,0)+basis(2,1) 
neg1 = basis(2,0)-basis(2,1)

(1/2) * pos1.trans().conj() * neg1

0j

In [19]:
#Orthongonality || | + > || ^ 2 = 1 
(1/2) * pos1.trans().conj() * pos1

(1+0j)

![title](images/ex2_3_3.png)

In [11]:
#Create/Implement a Z Pauli Operator 
zero = basis(2,0)
one = basis(2,1) 

#The conjugate tranpsoe of a matrix is = to the adjoint of a matrix
zero.trans().conj() == zero.dag()

True

In [18]:
# outer product of the 0 ket 
zero * zero.dag() # | 0 > < 0 |

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=True
Qobj data =
[[1. 0.]
 [0. 0.]]

In [22]:
#difference of the 0 and 1 ket outer product is equal to the z gate
sigmaz() == (zero * zero.dag()) - (one * one.dag())

True

![title](images/eq2_3_9png.png)

In [ ]:
#the sum of outer products in the same basis is equal to one. 
one 
two 
three 
F


![title](images/eq2_3_11.png)

![title](images/def2_3_5.png)

![title](images/def2_3_7.png)

![title](images/ex2_3_1.png)

![title](images/eq2_5_6.png)

![title](images/eq2_6_2_2_6_6.png)

![title](images/eq2_6_7_2_6_10.png)

![title](images/eq2_8_1_2_8_5.png)