In [1]:
#Chapter 2 Examples from "An Introduction to Quantum Computing" (Kaye, Leaflamme, Mosca)

#Worked with Qutip version 5.0.2 
#Numpy
#Juptyr Notebook 
#Scipy 1.13.1 
#(and potentially other libraries) 

#Daequan Peele 
#June 2024 

#Markdown cheat sheet:
#![title](images/imagename.png)

In [2]:
#imports
from qutip import *
import numpy as np


c:\Python312\Lib\site-packages\qutip\__init__.py:24: UserWarning: matplotlib not found: Graphics will not work.
  warnings.warn("matplotlib not found: Graphics will not work.")


In [ ]:
#Pauli Twirling
#Pauli errors are well studied in qec 
#easy to simute
#coherent errors are poorly studied
#hard to sim
#many ways to convert from Pauli to Coherent
#one method is p twirling 
#Pauli Twirling is correcting for coherence errors by performing a flip on the qubit 
#choose to apply x or not probabalistically on an error channel 
#positve and negative 


![title](images/ex2_1_1.png)

In [138]:
#left hand side of the equation
lhs = np.sqrt(2/3) * basis(4,1) + (1j/np.sqrt(3)) * basis(4,3)

In [4]:
#right hand side of the equation 
rhs = tensor(np.sqrt(2/3) * basis(2,0), basis(2,1)) + tensor(1j/np.sqrt(3) * basis(2,1), basis(2,1))

#prove that lhs and rhs are equal 
np.allclose(lhs[:],rhs[:])

True

In [5]:
#LHS and RHS are equivalent. 

![title](images/ex2_2_2.png)

In [5]:
#create vectors 
phi = np.sqrt(2/3) * basis(4,1) + (1j/np.sqrt(3)) * basis(4,3)
psi = np.sqrt(1/2) * basis(4,2) + np.sqrt(1/2) * basis(4,3)

In [7]:
#dot product of |phi>* and |psi> is equal to the inner product of <phi | psi> 
#|phi>* is the conjugate transpose of column vector |phi> 
dot_product = phi.trans().conj() * psi 
print(dot_product)

-0.4082482904638631j


In [8]:
#<phi|psi>
inner_product = psi.overlap(phi.trans().conj()) 
print(inner_product)

-0.4082482904638631j


In [9]:
#inner product and dot product of transposed phi are equivalent 
dot_product == inner_product

True

![title](images/ex2_2_4.png)

In [10]:
#Define basis vectors of Hilbert dimension 4 
b1 = basis(4,0) # |00>
b2 = basis(4,1) # |01>
b3 = basis(4,2) # |10>
b4 = basis(4,3) # |11>
#print(b1, b2, b3, b4)

In [11]:
#inner product check < x | y >
ip1 = b1.overlap(b2.trans().conj()) 
ip2 = b1.overlap(b3.trans().conj()) 
ip3 = b1.overlap(b4.trans().conj()) 

ip4 = b4.overlap(b3.trans().conj()) 
ip5 = b2.overlap(b4.trans().conj())

ip6 = b3.overlap(b4.trans().conj()) 

print(ip1,ip2,ip3,ip4,ip5,ip6) #print inner product of any normal vector

-0j -0j -0j -0j -0j -0j


In [12]:
#norm check  
#norm is the square root of the inner product of a vector with itself sqrt(< x | x >)
n1 = np.sqrt(b1.overlap(b1.trans().conj()))
n2 = np.sqrt(b2.overlap(b2.trans().conj())) 
n3 = np.sqrt(b3.overlap(b3.trans().conj())) 
n4 = np.sqrt(b4.overlap(b4.trans().conj())) 

print(n1,n2,n3,n4) #print norms of each basis vector 

(1-0j) (1-0j) (1-0j) (1-0j)


In [13]:
#All inner products of the basis vectors are 0 and all norms of the basis vectors are 1

![title](images/ex2_2_5.png)

In [14]:
#Equation written in qubit 
np.sqrt(2/3) * np.sqrt(1/2) * b2.overlap(b3.trans().conj()) 

+ np.sqrt(2/3) * np.sqrt(1/2) * b2.overlap(b4.trans().conj())

+ (-1j/np.sqrt(3)) * np.sqrt(1/2) * b4.overlap(b3.trans().conj()) 

+ (-1j/np.sqrt(3)) * np.sqrt(1/2) * b4.overlap(b4.trans().conj()) 

#This equation should equal the dot product (or inner product) obtained from 2.2.2 


-0.4082482904638631j

In [15]:
print(dot_product)

-0.4082482904638631j


![title](images/ex2_2_6.png)

In [6]:
#Hadamard Basis: 
(1/np.sqrt(2)) * (basis(2,0) + basis(2,1)) # |+> 

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0.70710678]
 [0.70710678]]

In [17]:
(1/np.sqrt(2)) * (basis(2,0) - basis(2,1)) # |->

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[ 0.70710678]
 [-0.70710678]]

In [18]:
#Normality = < + | - > = 0
pos1 = basis(2,0)+basis(2,1) 
neg1 = basis(2,0)-basis(2,1)

(1/2) * pos1.trans().conj() * neg1

0j

In [19]:
#Orthongonality || | + > || ^ 2 = 1 
(1/2) * pos1.trans().conj() * pos1

(1+0j)

![title](images/ex2_3_3.png)

In [11]:
#Create/Implement a Z Pauli Operator 
zero = basis(2,0)
one = basis(2,1) 

#The conjugate tranpsoe of a matrix is = to the adjoint of a matrix 
# |0>* = 0.conj().trans() = 0.dag()
#adjoint is represented by .dag() (dagger)
zero.trans().conj() == zero.dag()

True

In [18]:
# outer product of the 0 ket 
zero * zero.dag() # | 0 > < 0 |

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=True
Qobj data =
[[1. 0.]
 [0. 0.]]

In [22]:
#difference of the 0 and 1 ket outer product is equal to the z gate
sigmaz() == (zero * zero.dag()) - (one * one.dag())

True

![title](images/eq2_3_9png.png)

In [53]:
#the sum of outer products in the same basis is equal to the identity gate. 
#Hilbert Space 2, 2 Bases 
zero = basis(2,0) * basis(2,0).dag() # |0> 
one = basis(2,1) * basis(2,1).dag()  # |1>

sum([zero, one]) 

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=True
Qobj data =
[[1. 0.]
 [0. 1.]]

In [55]:

#Identity is represented by qeye(N), where N is the number of levels in Hilbert space 
qeye(2)

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dia, isherm=True
Qobj data =
[[1. 0.]
 [0. 1.]]

![title](images/eq2_3_11.png)

In [72]:
#T is an operator in some capacity (Pauli, Z, I, Y, etc.)
# (<phi| T.dag() |rho>).conj 
#choose H = 2 and T = Z gate 
#H* is the dual vector space 
phi = basis(2,0)
rho = basis(2,1) 
Tdag = sigmaz().dag()

Trho = Tdag * rho 
Tphi = sigmaz() * phi

phi.overlap(Trho) == rho.overlap(Tphi)

True

![title](images/def2_3_5.png)

In [79]:
#Unitary operators 
#Inverse of Z operator == the adjunct (dagger) of Z operator 
sigmaz().inv() == sigmaz().dag() # Z operator is Unitary

True

In [84]:
print("Is X operator Unitary?") 
print(sigmax().inv() == sigmax().dag())
#Unitary operator's adjunct * itself is equal to the identity operator
sigmax().dag() * sigmax()

Is X operator Unitary?
True


Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[1. 0.]
 [0. 1.]]

![title](images/def2_3_7.png)

In [ ]:
#Projectors
#Following definition: A vector |phi> is called an eigenvector of an operator T if T|phi> = c|phi> for some constant c. The constant c is called the eigenvalue of T corresponding to the eigenvector |phi>. 

In [101]:
#choose I as our linear operator 
I = qeye(2) 

print("Does I^2 == I?")
print(I**2 == I) #Identity operator is a projector on the vector space H = 2
print("Does I.dag() == I?")
print(I.dag() == I) #Identity operator is an orthogonal projector 

Does I^2 == I?
True
Does I.dag() == I?
True


![title](images/ex2_3_1.png)

In [152]:
#Tracing 
#The trace of a square matrix is defined as the sum of the entries on the main diagonal of said matrix. 
#If A, B, and C are square matrices of the same size, then 
#Tr(ABC) = Tr(BCA) 'cyclic' 
a = Qobj([[1,2,8],[2,4,5],[3,7,3]])
b = Qobj([[4,5,9],[3,6,7],[2,4,1]]) 
c = Qobj([[6,0,3],[1,8,9],[5,4,0]])

Quantum object: dims=[[3], [3]], shape=(3, 3), type='oper', dtype=Dense, isherm=False
Qobj data =
[[4. 5. 9.]
 [3. 6. 7.]
 [2. 4. 1.]]

In [136]:
print("Tr(ABC): ") 
print((a * b * c).tr())

print("Tr(BCA): ") 
print((b * c * a).tr())

Tr(ABC): 
(1734+0j)
Tr(BCA): 
(1734+0j)


In [135]:
(a * b * c).tr() == (b * c * a).tr()

True

In [ ]:
#End of notebook for now, will potentially return to tackle the last few problems as time goes on/as needed. 

#RESULTS: 
# Increased fluency with Qutip, linear algebra, and quantum gates/states 
# Adjunct is the congujte transpose of a matrix, more notes pending 
# 

![title](images/eq2_5_6.png)

In [151]:
zero = basis(2,0)
one = basis(2,1) 

 
h = (1/np.sqrt(2)) * Qobj([[1,1],[1,-1]])
h.overlap(zero.dag())

h.overlap(one.dag())


(-0.7071067811865475+0j)

![title](images/eq2_6_2_2_6_6.png)

![title](images/eq2_6_7_2_6_10.png)

![title](images/eq2_8_1_2_8_5.png)